### ISSUE TITLE
Please vote: Major refactoring of package names

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#240] opened 2015-01-24 23:47 UTC
In brief, the question to vote on is:

**Should we do a major refactoring of BioJava package name for the 4.0 release?** 
```The biojava code base contains package names containing *biojava3* . This should get changed to *biojava* only. In addition, for the protein structure modules the packages `org.biojava.bio.structure.*`should get changed  to `org.biojava.structure.*` ```

We did not conclude the discussion posted at http://mailman.open-bio.org/pipermail/biojava-dev/2014-October/007842.html . To summarize the main issues:

In favor of refactoring:
+ This makes the package names more consistent across the project and avoids the confusing *biojava3* when our release version is 4.0

Against refactoring
- This breaks backwards compatibility. 
- Transitive dependencies

Please post +1 in the comments below to express support for refactoring and -1 if you are against refactoring.

Please post all votes by Tuesday, 27th of January.

**Comment by andreasprlic** [comment] 2015-01-25 00:04
-1 Backwards compatibility is more important than a 100% consistent API. I know that refactoring in my IDE is a simple task, but will this be as obvious for our users?  Also, we need to update all documentation if we do this. In particular the structure modules have been mostly backwards compatible since their beginning in 2004. This would be the first time that you can't plug a Structure object loaded with a recent biojava into an older piece of software, without having to refactor that code.

**Comment by phidias51** [comment] 2015-01-25 00:57
+1 as a user and a kibitzer I'm not sure I get a vote, but if I do, I vote
making the module and the package changes. With a full version change you
kind of expect some level of incompatibility. If you need to upgrade, it's
not too difficult.

Mark

**Comment by josemduarte** [comment] 2015-01-25 11:41
+1 consistency and better structure for the future is worth a bit of doc changing now. Plus breaking of backwards compatibility is precisely why 3.x goes to 4.x, so I don't see an issue there

**Comment by dmyersturnbull** [comment] 2015-01-26 01:49
-1 I think the issue is transitive dependencies, not backwards incompatibility.
+1 in favor of merging the few classes in biojava3.structure to biojava.structure, or deleting them if they're not useful. This +1 holds uunless someone explains why we have both packages in the first place and has a strong objection to changing or deleting it. Are biojava3.structure.StructureIO and biojava3.structure.validation even used?

**Comment by heuermh** [comment] 2015-01-26 01:59
-1 on refactoring package names org.biojava3 --> org.biojava
+0 on refactoring package names org.biojava3 --> org.biojava4

See http://mailman.open-bio.org/pipermail/biojava-dev/2014-October/007847.html

**Comment by sbliven** [comment] 2015-01-26 08:53
-1 on refactoring package names org.biojava3
+1 on refactoring org.biojava.structure to org.biojava3.structure, if not now then for 5.0.0. I think we would **like** to break backwards compatibility soon (e.g. for #220), and like @dmyersturnbull I dislike having two packages in the structure module.

**Comment by josemduarte** [comment] 2015-01-26 09:24
I think something needs clarification @dmyersturnbull . At the moment the situation with package names is:

- structure module: most packages are `org.biojava.bio.structure.*` except for 2 packages using `org.biojava3.structure`
- all other modules: `org.biojava3.modulename.*`

Thus the one module that doesn't follow the convention at the moment is __structure__, since most of its packages are using the older `org.biojava.bio.structure.*`.

Perhaps we should split the vote to choose from all the possible solutions. I'll go from most conservative to most disrupting:

1. Keep existing situation
2. Rename `org.biojava.bio.structure.*` to `org.biojava3.structure`: i.e. keep the biojava3 naming but making the whole project consistent
3. Rename all packages to `org.biojava.modulename.*` (original solution proposed above): this has issues with transitivity, as explained by @heuermh , see http://mailman.open-bio.org/pipermail/biojava-dev/2014-October/007847.html
4. Rename all packages to a new namespace that was never used before, e.g. `org.biojavax.modulename.*`: this avoids the transitivity issues

**Comment by josemduarte** [comment] 2015-01-26 09:27
My vote goes to 4 which is in my opinion the most complete solution. I'm happy to compromise and stay with 3 or 2, but definitely not with 1.

**Comment by sbliven** [comment] 2015-01-26 09:34
Please vote on the related #242 as well!

**Comment by paolopavan** [comment] 2015-01-26 14:18
if I could add my opinion, I would vote for refactoring biojava3 to biojava4; then 5 and so on.
I see some advantages: 
1) the very same nature of semantic versioning implies that major updates (given a version X.Y.Z, those in the first nuber X) are not backward compatible. Indeed, this is **already the case** since for example the introduction of CompoundNotFoundException in the constructor of AbstractSequence will break all existing projects and will compel developers to update their code to handle the exception.
2) using such a namespace as biojava4 could allow to some programmers to include both libraries biojava3 and biojava4 if actually needed.
3) Even if I'm not very very in deep with git, but i suspect that branching biojava4 instead of keeping it in the same line of development will allow to release bug fixes committed to biojava4 also to compatible codes in biojava3 allowing some kind of mantainance until possible.
4) This is the same approach used in many projects, for example python language itself. Will prevent unnecessary major version increasing and help version scheduling: api breaking changes goes in next major, non breaking changes goes in minor.

Moreover this solution solves also the other issue.

Just my two cents.

**Comment by andreasprlic** [comment] 2015-01-26 15:26
I don;t know any other project that versions package namespaces and changes them in sync with the major release number. The would require refactoring by every user at every major version upgrade. Pain!

**Comment by heuermh** [comment] 2015-01-26 16:01
Many of the Apache Commons libraries do
http://commons.apache.org/proper/commons-lang/
http://commons.apache.org/proper/commons-math/
http://commons.apache.org/proper/commons-collections/

One that does not and often causes runtime breakage due to version mismatches in transitive dependencies is Guava
https://code.google.com/p/guava-libraries/

They explicitly advertise this as a feature though:
"In contrast to the JDK -- which maintains extremely strict backwards compatibility even for its worst mistakes -- Guava deprecates, and yes, deletes unwanted features over time."
https://code.google.com/p/guava-libraries/wiki/PhilosophyExplained

**Comment by paolopavan** [comment] 2015-01-26 16:22
About the version in namespace you're are right, Andreas (exept for biojava itself, of course ;-) ). 
But it is also true that the introduction of CompoundNotFoundException by itself (or elements like that, I'm not discussing the opportunity of the modofication) will require a code refactoring by every user for this major release. And not an automatic one, but manual! 
The only way to avoid user side refactoring for this very release in my opinion is to keep non api breaking improvements with the namespace biojava3 and separe api breaking and project evolutions in the new one: biojava4.

Of course the decision is yours, it is more a matter of interpretation of the versioning system. People will know that if they don't want do touch existing code, they must stick with biojava3 and periodical patches. 
Apple has always do this way for their core frameworks (carbon, cocoa, for example) limiting backwards compatibility and for this they have never been so loved by developers. But on the contrary they have mantained a lightweight and state of the art operative system. 
As far as I know Mozilla does the same with firefox.

Well anyway, I hope I made myself clear! It was just to express my personal opinion, I don't want to make any pressure or drive any decision! I will continue to have fun bioJava-ing :-)

**Comment by dmyersturnbull** [comment] 2015-01-26 19:18
@josemduarte Just adding my suggestion to your list of options:

  1-1. A cross between options 1 and 2: move the two packages in org.biojava3.structure to org.biojava.bio.structure. This does mean that biojava-structure is the only module that doesn't follow the org.biojava3 convention, but it also means virtually nothing breaks. We could then reconsider a more drastic renaming for Biojava 5 (e.g. org.biojava5).

**Comment by sbliven** [comment] 2015-01-27 08:23
So what's the consensus procedure on these? If everyone keeps adding suggestions then the voting system doesn't really work.

**Comment by josemduarte** [comment] 2015-01-27 12:00
In an attempt to save the vote, I've opened a new one (#245) which contains all the solutions proposed above. If that doesn't work either, then @andreasprlic can take the decision.

**Closed** 2015-01-27 14:19 UTC
Labels: question, urgent

**Comment by andreasprlic** [comment] 2015-01-27 14:56
I want to thank everybody who made the effort to contribute and comment here. It is great to see that so many people want to be involved in this. As to the original question of this vote, I think it is clear that there is neither a consensus, nor a majority in favor of the original proposal. However that does not mean that the proposal is not valued. In the course of this discussion a couple of interesting comments and suggestions were made. Let's continue to discuss these further on #245.
