### ISSUE TITLE
Remove external test dependency

### ISSUE THREAD

**Issue by lee-mcfaul** [biojava/biojava#831] opened 2019-02-19 21:08 UTC
During some debugging of another test I submitted a few commits back to back and encountered the error bellow. It essentially means that we hit a quota for downloads from https://eutils.ncbi.nlm.nih.gov over a certain period of time and this caused the test to fail. 

I don't think that there should be a unit test that depends on an external resource with a quota as this can cause failing builds when there's nothing actually wrong with the build.

`[INFO] Running org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest
20:50:48 [main] ERROR org.biojava.nbio.core.sequence.ProteinSequence - Caught IOException when getting DNA sequence for id NC_000932.1. Error: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=nuccore&id=NC_000932.1&rettype=fasta&retmode=text
[ERROR] Tests run: 16, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 24.089 s <<< FAILURE! - in org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest
[ERROR] testProteinSequenceFactoring[0](org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest)  Time elapsed: 0.54 s  <<< ERROR!
java.net.ConnectException: Connection refused (Connection refused)
	at org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest.testProteinSequenceFactoring(GenbankProxySequenceReaderTest.java:135)
[ERROR] testProteinSequenceFactoring[2](org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest)  Time elapsed: 0.051 s  <<< ERROR!
java.io.IOException: Server returned HTTP response code: 429 for URL: https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=protein&id=379015144&rettype=gb&retmode=text
	at org.biojava.nbio.core.sequence.loader.GenbankProxySequenceReaderTest.testProteinSequenceFactoring(GenbankProxySequenceReaderTest.java:135)`

**Comment by lafita** [comment] 2019-02-19 22:33
We are aware of the issue and have had some discussion before in #606. Unless the test check the access to a remote resource, files should be included in the library.

I have also seen that a fix was made for this test already in ed7fb66. Could you take a look and see if you can fix it? Thanks!

**Comment by josemduarte** [comment] 2019-02-19 22:55
This test has been causing a lot of pain. It'd be great to make it independent of the external resource. Thanks @lee-mcfaul

**Comment by josemduarte** [comment] 2019-09-02 17:36
Closing as a duplicate of #606

**Closed by josemduarte** 2019-09-02 17:36 UTC
