### ISSUE TITLE
Make loading of structures more consistent

### ISSUE THREAD

**Issue by dmyersturnbull** [biojava/biojava#81] opened 2013-11-30 22:54 UTC
Right now, loading of data from SCOP, CATH, and AtomCaches is handled very differently. It would be nice to have 1) an interface that is more consistent between SCOP and CATH, and 2) a more robust way to load arbitrary "structures" given unique identifiers.

**Comment by sbliven** [comment] 2015-01-20 13:53
I'm adding this to the 4.0.0 milestone, since it will add a lot of methods and is closely related to #237.  Let's git 'er done!

**Comment by sbliven** [comment] 2015-01-20 14:20
I feel like what I really want here is a full-blown selection logic. `StructureIdentifier` implementations should be a set of methods which map from a String (either a short unique ID, as in domains) to some sort of unambiguous, memory-compact structure query.

Currently we support queries which contain a unique PDB ID and one or more sequential sequences of residues. Is there a way we could generalize this to extract any arbitrary subset of a Structure? `StructureIdentifier` operators could be applied on any level of the `Structure` hierarchy (with more levels potentially being added by #220):

1. PDB ID
2. Model
3. Chain
4. Residue
5. Atom

The problem is that the representation needs to be compact, unambiguous, and independent of the Structure it applies to.

**Comment by pwrose** [comment] 2015-01-20 21:33
How about:

Without model specification:
<pdbid>.<chainid>.<residueid>.<atomname>.<alternative location id>

With model specification (consider pdbid as an array of models),
<pdbid>[modelnumber].<chainid>.<residueid>.<atomname>.<alternative location
id>

residue id would need optionally include a residue number and insertion
code:
ASP - any ASP
ASP25 -  with residue number
ASP25C - with residue number and insertion code

atom name:
CA - C alpha
CA.A - C alpha alternative location A

-Peter

**Comment by dmyersturnbull** [comment] 2015-01-20 21:55
I think the selection logic needs to be non-hierarchical. Otherwise, (e.g.) to specify the backbone of 1HIV, we would need "1HIV.A.1.CA, 1HIV.A.2.CA, ..., 1HIV.A.n.CA, 1HIV.B.1.CA, 1HIV.B.2.CA, ..."

Perhaps Identifier can hold a PDB id and an order-independent set of Selection objects, where each Selection has a unique string representation. For example, an Identifier for the above case could store pdbId = "1HIV" and the Selection object "#CA", where "#" selects atoms.

For more complex cases, such as selecting just CA atoms of chain A but all atoms of chain B, we could permit nesting of Selection objects or an aggregate Selection type.

We could have a Selection interface with a single apply(Structure) method.
And several concrete Selection implementations:
 - ModelSelection
 - ChainSelection: ".A" or ".1" or ".A-C"
 - AtomSelection: "#CA" or or "#CA-N" "#1-2"
- ComplexSelection, which would allow nesting by holding two or more Selections.

So the operation relating the root-level Selection objects in the Identifier would be union, while the Selection objects in a ComplexSelection would be intersection-ed.

This would allow arbitrary selection with a compact representation. For example, the complex case described above could be represented as:
Identifier {
pdbId="1HIV"
selections={".B-", ComplexSelection{".A", "#CA"}}
}

We would need to formulate the rules precisely so that representations are unique.

(I'm sure I made mistakes above, so point them out if you see them.)

**Comment by sbliven** [comment] 2015-01-21 14:44
PyMOL is able to do fairly well with a heirarchical selection string by allowing ranges and treating missing levels as matching everything. E.g. `/1HIV//A//CA` for @dmyersturnbull's first case, `/1HIV//A/1-15` for the first few residues, etc. However, to specify sections of two different chains you have to use a boolean operator, e.g. `/4HHB//A/1-15 or /4HHB//B/30-45`.

I guess with the current syntax we're treating `,` as an implicit 'or', e.g. `4HHB_A:1-15,B:30-45`. All possible selections can be expressed as a union of selectors, although allowing parentheses and nesting can make the syntax much more compact.

@dmyersturnbull I think you switched 'union' and 'intersection' in the fifth paragraph, but I know what you mean. Also, unions would definitely be implemented as something like the ComplexSelection you propose, but it would still need a clear string representation.

I'm currently changing the StructureIdentifier interface to work more like you described, with a reduce(Structure) method to apply the selection. I won't extend or modify the syntax for the moment, but it will be easy to add such selections in the future.

**Comment by dmyersturnbull** [comment] 2015-01-21 20:06
> @dmyersturnbull I think you switched 'union' and 'intersection' in the fifth paragraph

I actually had in mind that each Selection would have an apply() method, which would add another set. That way, to get the backbones of chains A and B, you could have:
selections = {ComplexSelection{".A", "#CA"}, ComplexSelection{".B", "#CA"}}, which could be represented as:
".A#CA,.B#CA", where , is union. This way, you don't have to worry about parentheses, since intersection has higher precedence.

So I had in mind the opposite of what I think you do (with your reduce() method), though I can see an argument in favor of either approach. 

> PyMOL is able to do fairly well with a heirarchical selection string by allowing ranges and treating missing levels as matching everything.
With missing levels matching as wildcards, that seems like a good approach. Do you think Pymol's notation is sufficient for our needs? If so, I'm totally in favor of using it.

> I'm currently changing the StructureIdentifier interface to work more like you described, with a reduce(Structure) method to apply the selection.
ScopDomain and CathDomain both implement StructureIdentifier but know nothing about Structures. Perhaps it would be better to give StructureIdentifier an union(Selection), add(Selection), or reduce(Selection) method that returns a new StructureIdentifier, or to give Selection a reduce(StructureIdentifier) method (that returns a new StructureIdentifier). Then we can add a method StructureTools.getStructure(StructureIdentifier) that just calls getStructure(structureIdentifier.toString()). This way, StructureIdentifiers can be used independently of Structures.

> We would need to formulate the rules precisely so that representations are unique.
I should have included an example:
With the notation above, ".1-" (any chain after the first, inclusive) would be the same as "" (everything). So Selection(".A-").equals(Selection("")) should return true. For this, we need a set of rules to simplify the selection algebra to its most compact form, and that logic should probably happen in the Selector constructor.

**Comment by sbliven** [comment] 2015-01-29 10:28
Despite strong attempts to be fully backwards compatible with `AtomCache.getStructure(String)`, I think a few syntaxes should be dropped here in the name of consistency:

* colon range separators (`4hhb:A:10-20`)
* Parenthesized ranges (`4hhb(A:10-20)`)
* Accessing chains by index (since numbers are valid chainIds) (`4hhb:1`)

These are included in `TestAtomCache.testAtomCacheNameParsing()`, but I think they were mostly there to document the current implementation.

The third one is the only use that might actually be used & useful. An alternative, if we want to keep the behavior, would be to print a warning message when numeric chain IDs are treated as 1-based indices, similar to the behavior for lower-case chainIds.

**Comment by sbliven** [comment] 2015-01-29 18:56
This is mostly implemented in my fix81 branch: https://github.com/sbliven/biojava-sbliven/tree/fix81

It adds StructureIdentifiers and switches most of the structure parsing onto them.

**Comment by sbliven** [comment] 2015-01-29 21:02
Ok, this isn't going to be ready for this release. I don't think it's enough of an API change that it will require a major version bump, although it would have been nice for 4.0.0. Let's take our time and discuss it thoroughly.

**Comment by andreasprlic** [comment] 2015-01-29 21:06
agreed, as just discussed via skype.

**Comment by sbliven** [comment] 2015-02-03 11:27
Current status: my fix81 branch currently builds and passes tests. It also finishes a couple of things that were hastily dropped from the 4.0.0 release, like deprecated support for chain indices (e.g. "4hhb.0" being an alias for "4hhb.A"). However, I'd like to discuss the basic architecture and some strengths/weaknesses I see. I'll try to play devil's advocate for my own code here.

**1.** `StructureIdentifiers` don't know how to fetch structures directly. Instead, they just provide the `getPdbId()` method, which allows AtomCache to fetch the structures. However, when loading structures from files and urls the PDB ID is not known. Thus, AtomCache needs to treat these as special cases and try to do the right thing based on the identifier, which breaks the abstraction and leads to duplicate code between the `StructureName(String)` constructor and `AtomCache.getStructure(String)`.

One solution would be to change `getPdbId()` to `getStructure()`, with most implementations delegating to `AtomCache`. This would need some care to remove any circularities, since `AtomCache.getStructure()` currently converts things into a StructureIdentifier.

**2.** I thought that there should be a canonical way for representing structures in biojava, so that arcane identifiers like 'SCOP:127355' can be turned into '2av3.A:2-146'. This means singling out one implementation as a privileged format, and making sure all other implementations know how to convert themselves to that. However, the current candidate for canonical format, `SubstructureIdentifier`, is limited to dealing with residues, doesn't know about models, etc. So what's the way to future-proof the `toCanonical()` method? Rename `SubstructureIdentifier` to `CanonicalIdentifier` and commit to making future syntax additions backwards compatible? Create a new language which we hope encapsulates all the info we might want to express in the future?

**3.** I'm open to ideas for other versions of the `reduce(Structure)` method. For instance, since the current formulation discards information, implementing a union identifier would require more than just calling reduce() on the operands and then unioning the results (or at least that would be inefficient). Maybe there's a dual formulation that leads to cleaner implementations?

**4.** AtomCache has parameters for handling matching ligands to chains (e.g. following PDB-format chains, using mmcif-specific attributes, or matching ligands based on distance or chemical properties). The reduce methods should be somewhat aware of these properties, to allow chain-specific selections. Right now it's handled as a post-reduce step by some AtomCache methods.

**5.** Exception handling in `StructureName.realize()` is bad. Some exceptions are logged and ignored (following the PDPParser interface, which doesn't declare any exceptions).

**Comment by andreasprlic** [comment] 2015-06-25 00:23
not sure why still open, closing again.

**Comment by josemduarte** [comment] 2015-11-21 00:57
So if I understand the conversation above @sbliven, your [fix81](https://github.com/sbliven/biojava-sbliven/tree/fix81) has not been merged, is that right? 

I am trying to solve a separate issue, where the current `StructureName` implementation does not cope with multi-letter chain ids. Before trying to fix that in the current implementation, I think it's worth giving the full solution here another go. I suppose this solution would be able to cope with multi-letter chain ids, wouldn't it? 

Are there any major obstacles for merging this in? From the points you give above I don't see anything as a major obstacle. Some of the points will still need to be worked on after the merge, but I think if we merge it we can only gain much better support for structure identifiers. With the current system we really have a few limitations (e.g. multi-letter chain ids).

**Comment by lafita** [comment] 2015-11-23 10:10
I also vote for merging in the changes, because I would like to use the `StructureIdentifier` for naming **protodomains** (symmetric subunits), and the current implementation does not work (see the issue #297), but I do not want to modify it either. We can always fix problems after the merge.

**Comment by sbliven** [comment] 2015-12-02 14:26
Update: I set this code aside too long ago, and they don't merge cleanly. I need to redo some parts of my old branch to make sure I don't overwrite any of the intervening development. I hope to have this done in a week or two, definitely for the next release.

**Comment by sbliven** [comment] 2016-01-25 11:11
OK, with the merge of #376 I think this can be closed. There are still many places that could take better advantage of the new StructureIdentifier class, but these can be added over time.

**Closed by sbliven** 2016-01-25 11:11 UTC
Labels: enhancement
