### ISSUE TITLE
Finding protein classifications

### ISSUE THREAD

**Issue by lukeczapla** [biojava/biojava#690] opened 2017-07-17 22:35 UTC
Hi guys,

I am working on using CATH and SCOP for finding protein domain classifications.  I am able to get results for older PDB structures with the Scop and Cath Installations but I was wondering if there's anything in BioJava that has directly addressed classifying new proteins (structures from 2015 that are missing CATH and SCOP information in the database like 5AV9 but are clearly related to classified structures like 1KX5).  On the web, there are some CATH sites that accept new queries and find matches.  If nothing is directly doing this, I can try to write a routine for that in BioJava.

The idea would be matchSCOP or matchCATH method, to take a chain and return the CATH or SCOP record of another protein that has a high enough percentage match.  The alignment tools will be super helpful.  Since switching to CATH hasn't helped fix this problem of missing information, I can do it within SCOP which I understand better.

Thanks
Luke

**Comment by sbliven** [comment] 2017-07-18 09:39
Extending existing classifications is currently not implemented in BioJava. The problem is that identifying the homologue can be quite costly, both in terms of downloading the sequences to be searched and in actually finding homologues (e.g. via blast). For this reason BioJava has left fast homology detection to external tools and just focused on parsing the results.

One thing that could help would be support for CATH's daily releases. These should be fully up-to-date with the PDB (although it doesn't help users with custom structures). I think this would be relatively easy to implement. There is already a strong mechanism for requesting particular SCOP(e) and CATH versions (since the default in the code tends to lag behind the latest release). Unfortunately it looks like both the Berkeley and Cambridge forks of SCOP are being phased out due to lack of funding, so they're unlikely to have additional releases.

You might also look into using ECOD. They're typically only 2-3 weeks behind the PDB, and BioJava has good support.

**Comment by lafita** [comment] 2018-03-11 20:26
Should we close this one then? Is better support for homologue identification something we plan to include in BioJava? 

I feel that this can be done in a few steps with the current methods in the library, so I would suggest creating a small demo or cookbook entry explaining how to do it.

**Comment by sbliven** [comment] 2018-03-15 10:03
This sounds like a downstream project to me. It requires a fast one-to-many sequence search, which BioJava doesn't have at the moment. If someone is interested in implementing that in Java we could revisit, but for now I think searching and clustering is best done with an external tool an then read into BioJava.

Let's close for now.

**Closed by sbliven** 2018-03-15 10:03 UTC
Labels: enhancement, help wanted, new feature
