### ISSUE TITLE
Does IOTools.readEMBL  parse "db_xref" tags of the input EMBL file?

### ISSUE THREAD

**Issue by esmat-hejazi** [biojava/biojava#1068] opened 2023-06-27 12:54 UTC
##### I am using BioJava library to parse an EMBL file and get the sequences.
`SeqIOTools.readEmbl(bufferedReader); ` 
##### There is another method with the same name from IOTools that returns the sequences preserving their order:

```
SymbolTokenization tokenization = RichSequence.IOTools.getDNAParser();
Namespace namespace = RichObjectFactory.getDefaultNamespace();
SimpleRichSequenceBuilder builder = new SimpleRichSequenceBuilder();
RichSequenceBuilderFactory factory = RichSequenceBuilderFactory.FACTORY;
SequenceIterator sequences = IOTools.readEMBL(bufferedReader, tokenization, factory, namespace);
```

##### Where am I making mistake? How do I get the EMBL sequences sorted and fully parsed?

**Comment by josemduarte** [comment] 2023-06-27 21:53
I don't find the referred method (`readEMBL`) or the classes `SeqIOTools` or `IOTools`. Is this from current biojava or from a previous version? or perhaps from biojava-legacy?

In current biojava for EMBL there is: `org.biojava.nbio.core.sequence.io.embl.EmblReader` from biojava-core module.

**Comment by esmat-hejazi** [comment] 2023-06-28 08:17
Yes, they are in the `biojava-legacy`. But the `EmblReader` class in `biojava-core`, does not parse the **CDS tags**, so does not populate the **translation Sequences**. I need something that gives me all the sequences in the exact same order of the input Embl file. 
`SeqIOTools or IOTools`, both parse the **CDS tags**, but `IOTools `do not parse **db_xref tag in CDS tag**, and `SeqIOTools` do not return the sequences in the same order of the input file, which is odd cause the Embl file itself is ordered.

The following Image, shows some examples of **CDS tags**:

<img width="741" alt="image" src="https://github.com/biojava/biojava/assets/26109613/9925f01a-b863-4ea7-89ed-642106c5fb16">

**Comment by esmat-hejazi** [comment] 2023-06-28 09:56
The same problem in org.biojava.nbio.core.sequence.io.embl.EmblReader from biojava-core module is mentioned here:  [#923](https://github.com/biojava/biojava/issues/923)

**Comment by josemduarte** [comment] 2023-07-14 22:43
Alright, so it looks like the functionality is not available in current biojava. We'd definitely welcome pull requests on this. 

In any case, I'll close this as a duplicate of #923

**Closed** 2023-07-14 22:43 UTC
