### ISSUE TITLE
request: more information on "Unable to retrieve request ID"

### ISSUE THREAD

**Issue by Queuebee2** [biojava/biojava#866] opened 2020-04-10 14:53 UTC
https://github.com/biojava/biojava/blob/18f57de72a271ae5cbff6f586ee83831089f54fd/biojava-ws/src/main/java/org/biojava/nbio/ws/alignment/qblast/NCBIQBlastService.java#L230

I keep running into this problem and can't seem to find any documentation on what it means exactly and what I should do (if there's a possible workaround).

Could it mean our IP is banned or that NCBI servers are overloaded or that there is no connection?

I ask this here as I couldn't find another place to post questions, except maybe the Biojava discussion list? Please excuse me if this isn't the right place for these type of questions!

**Comment by josemduarte** [comment] 2020-04-12 23:33
It could well be that ncbi is returning a 429 code (too many requests). They've been doing that for more than a year now.

The problem here is not so much the error message in line 230, but rather that the code in `NCBIQBlastService` does not seem to be checking that http code 200 is returned. That's really a bug. Would you be able to submit a pull request?

**Comment by Queuebee2** [comment] 2020-04-13 04:10
I'm afraid I don't have a clue how to fix such a thing right now, but I'll try looking in to it and asking around for help.

**Comment by josemduarte** [comment] 2021-03-11 17:20
@MaxGreil could you help with this one?

**Comment by MaxGreil** [comment] 2021-03-13 11:12
Hi @josemduarte , I can have a look at this issue.

However, I tried with test `NCBIQBlastServiceDemo` and did not get the same exception.

Do you have a minimal working example to reproduce this bug?

**Comment by Queuebee2** [comment] 2021-03-13 14:52
Oh my, It's been almost a year. I must say that I didn't have much of a clue of what I was doing back then and still don't. I created this MWE to test it again.

### In a file `UnableToRetrieveIDErrorMWE.java`:
```java
import org.biojava.nbio.ws.alignment.qblast.BlastProgramEnum;
import org.biojava.nbio.ws.alignment.qblast.NCBIQBlastAlignmentProperties;
import org.biojava.nbio.ws.alignment.qblast.NCBIQBlastService;

public class UnableToRetrieveIDErrorMWE {

    static String theFasta = "> ORF:Glennie_the_platypus.fa:44:91:2\n" +
            "ATGGGGAGGGAGGAGTTCAAGCAGAGGCCTACCCATTTCCATTCCTAGC";

    public static void main(String[] args) {

        NCBIQBlastService service = new NCBIQBlastService();
        NCBIQBlastAlignmentProperties alignmentProps = new NCBIQBlastAlignmentProperties();
        
        alignmentProps.setBlastProgram(BlastProgramEnum.blastn);
        alignmentProps.setBlastDatabase("nt");

        String rid = null;
        
        try {
            rid = service.sendAlignmentRequest(theFasta, alignmentProps);

            while (!service.isReady(rid)) {
                System.out.println("waiting for results. zzz");
                Thread.sleep(5000);
            }
            System.out.println("results are in!" + rid);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
```

### and here are the `pom.xml` dependencies used:
```xml
    <dependencies>
        <dependency>
            <groupId>org.biojava</groupId>
            <artifactId>biojava3-core</artifactId>
            <version>3.0</version>
        </dependency>
        <dependency>
            <groupId>org.biojava</groupId>
            <artifactId>biojava-genome</artifactId>
            <version>4.2.0</version>
        </dependency>

        <dependency>
            <groupId>org.biojava</groupId>
            <artifactId>biojava-structure</artifactId>
            <version>4.2.0</version>
        </dependency>
        <dependency>
            <groupId>org.biojava</groupId>
            <artifactId>biojava-ws</artifactId>
            <version>5.3.0</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>biojava-maven-repo</id>
            <name>BioJava repository</name>
            <url>http://www.biojava.org/download/maven/</url>
        </repository>
    </repositories>
```

One solution I tested is not to actually send the full contents of a fasta file as a String, but only single sequences. I guess that is the way it's intended to be used (?). The [`NCBIQBlastServiceDemo `](https://biojava.org/docs/api5.0.0/src-html/demo/NCBIQBlastServiceDemo.html#line.38) uses only a single string, but at [Nucleotide BLAST](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastSearch) it's possible to add a fasta with multiple sequences. We didn't understand this a year back and thought we could send it to blast this way. I think we confused the way it worked with how [`biopython`'s package`](https://biopython.org/docs/1.75/api/Bio.Blast.NCBIWWW.html) works, which allows for a full fasta file to be sent. (multiple headers + sequences)

I think with this I've only proven to myself that `NCBIQBlastService` works fine with single sequences. Maybe the documentation can be expanded to include an example to blast multiple sequences, or rather, all sequences within a file.

**Comment by josemduarte** [comment] 2021-03-16 05:19
Indeed `NCBIQBlastService` requires just a sequence or a ncbi id, the javadocs are very clear:
```
* @param query : a {@code String} representing a sequence or Genbank ID
```
So there seems to be no issue here at all. Let's close it then.

BTW @Queuebee2 your pom file looks a bit odd. You should be using the same biojava version across and best would be to  use the most recent available (5.4.0)

**Closed by josemduarte** 2021-03-16 05:19 UTC
Labels: bug

**Comment by GP-sir** [comment] 2022-12-04 06:09
It confuseed me for few times to blast multiple sequences, finally，I found the reason why we could not  blast multiple sequences use NCBIQBlastService and fixed it. when we send fasta format   multiple sequences like  `rid = service.sendAlignmentRequest(fastaSequence, props);`, fastaSequence : >geneid1\n ATCG....>geneid2\n ATCG...   ,  it is important that \n need to URLENCODE.  You can use URLUtil.encode "cn.hutool.core". Like, ` rid = service.sendAlignmentRequest(URLUtil.encode(fastaSequence), props);`

**Comment by GP-sir** [comment] 2022-12-04 06:09
> Oh my, It's been almost a year. I must say that I didn't have much of a clue of what I was doing back then and still don't. I created this MWE to test it again.
> 
> ### In a file `UnableToRetrieveIDErrorMWE.java`:
> ```java
> import org.biojava.nbio.ws.alignment.qblast.BlastProgramEnum;
> import org.biojava.nbio.ws.alignment.qblast.NCBIQBlastAlignmentProperties;
> import org.biojava.nbio.ws.alignment.qblast.NCBIQBlastService;
> 
> public class UnableToRetrieveIDErrorMWE {
> 
>     static String theFasta = "> ORF:Glennie_the_platypus.fa:44:91:2\n" +
>             "ATGGGGAGGGAGGAGTTCAAGCAGAGGCCTACCCATTTCCATTCCTAGC";
> 
>     public static void main(String[] args) {
> 
>         NCBIQBlastService service = new NCBIQBlastService();
>         NCBIQBlastAlignmentProperties alignmentProps = new NCBIQBlastAlignmentProperties();
>         
>         alignmentProps.setBlastProgram(BlastProgramEnum.blastn);
>         alignmentProps.setBlastDatabase("nt");
> 
>         String rid = null;
>         
>         try {
>             rid = service.sendAlignmentRequest(theFasta, alignmentProps);
> 
>             while (!service.isReady(rid)) {
>                 System.out.println("waiting for results. zzz");
>                 Thread.sleep(5000);
>             }
>             System.out.println("results are in!" + rid);
>         } catch (Exception e) {
>             e.printStackTrace();
>         }
>     }
> }
> ```
> 
> ### and here are the `pom.xml` dependencies used:
> ```
>     <dependencies>
>         <dependency>
>             <groupId>org.biojava</groupId>
>             <artifactId>biojava3-core</artifactId>
>             <version>3.0</version>
>         </dependency>
>         <dependency>
>             <groupId>org.biojava</groupId>
>             <artifactId>biojava-genome</artifactId>
>             <version>4.2.0</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.biojava</groupId>
>             <artifactId>biojava-structure</artifactId>
>             <version>4.2.0</version>
>         </dependency>
>         <dependency>
>             <groupId>org.biojava</groupId>
>             <artifactId>biojava-ws</artifactId>
>             <version>5.3.0</version>
>         </dependency>
>     </dependencies>
>     <repositories>
>         <repository>
>             <id>biojava-maven-repo</id>
>             <name>BioJava repository</name>
>             <url>http://www.biojava.org/download/maven/</url>
>         </repository>
>     </repositories>
> ```
> 
> One solution I tested is not to actually send the full contents of a fasta file as a String, but only single sequences. I guess that is the way it's intended to be used (?). The [`NCBIQBlastServiceDemo `](https://biojava.org/docs/api5.0.0/src-html/demo/NCBIQBlastServiceDemo.html#line.38) uses only a single string, but at [Nucleotide BLAST](https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE_TYPE=BlastSearch) it's possible to add a fasta with multiple sequences. We didn't understand this a year back and thought we could send it to blast this way. I think we confused the way it worked with how [`biopython`'s package`](https://biopython.org/docs/1.75/api/Bio.Blast.NCBIWWW.html) works, which allows for a full fasta file to be sent. (multiple headers + sequences)
> 
> I think with this I've only proven to myself that `NCBIQBlastService` works fine with single sequences. Maybe the documentation can be expanded to include an example to blast multiple sequences, or rather, all sequences within a file.

It confuseed me for few times to blast multiple sequences, finally，I found the reason why we could not  blast multiple sequences use NCBIQBlastService and fixed it. when we send fasta format   multiple sequences like  `rid = service.sendAlignmentRequest(fastaSequence, props);`, fastaSequence : >geneid1\n ATCG....>geneid2\n ATCG...   ,  it is important that \n need to URLENCODE.  You can use URLUtil.encode "cn.hutool.core". Like, ` rid = service.sendAlignmentRequest(URLUtil.encode(fastaSequence), props);`
