### ISSUE TITLE
How to calculate distance matrix from multiple alignment file for DNA

### ISSUE THREAD

**Issue by HounerX** [biojava/biojava#911] opened 2021-01-06 00:12 UTC
Hello, 
        I hope everyone is doing good.  I am really confused about the difference between multiple sequence alignment object and Msa.  I want to create a distance matrix after I aligned. I keep getting errors. I would really appreciate it if the cookbook can go a little in depth with  multiple sequence alignment . 

     

```
Profile<DNASequence, NucleotideCompound> profile = Alignments.getMultipleSequenceAlignment(lst); //I aligned and made profile earlier

MultipleSequenceAlignment <DNASequence, NucleotideCompound> msa = new MultipleSequenceAlignment<DNASequence, NucleotideCompound>();

int size_of_aligned_sequences=profile.getAlignedSequences().size();
Object[]  repeat_clusters = profile.getAlignedSequences().toArray();

System.out.println(repeat_clusters[0]);
for(int i=0; i<size_of_aligned_sequences;i++) {
	DNASequence dna = new DNASequence(repeat_clusters[i].toString()); 

	msa.addAlignedSequence(dna);
}

DistanceMatrix DM = PairwiseDistanceCalculator.calcKimuraDistances(msa); // I get error here
```
Thank you so much.

**Comment by josemduarte** [comment] 2021-01-11 21:53
There is an example [`DemoDistanceTree`](https://github.com/biojava/biojava/blob/master/biojava-alignment/src/main/java/demo/DemoDistanceTree.java) in the demo package of biojava-alignment module. Does that help at all? If not could you post the error you are seeing?

**Comment by sbliven** [comment] 2021-03-01 17:15
The problem is that Biojava and forester use different MSA classes. `PairwiseDistanceCalculator` is a forester method and expects `org.forester.msa.Msa` objects, not `org.biojava.nbio.core.sequence.MultipleSequenceAlignment`. Fortunately BioJava provides a wrapper. Use 
```
import org.biojava.nbio.phylo.DistanceMatrixCalculator;

DistanceMatrix DM = DistanceMatrixCalculator.kimuraDistance(msa);
```

**Comment by josemduarte** [comment] 2021-03-11 17:18
@HounerX I'll close this one. If something is still unclear, please reopen.

**Closed by josemduarte** 2021-03-11 17:18 UTC
Labels: question
