### ISSUE TITLE
Exception thrown when more than 2 beta bridges found while assigning secondary structure

### ISSUE THREAD

**Issue by abradle** [biojava/biojava#360] opened 2016-01-05 00:30 UTC
Hi,

I'm using the latest git version of Biojava (commit 4dadf22bfb38a7a9df13b051652935d064d83bf9) and I'm gettign an error on secondary structure prediction for pdb code 2K4T (amongst others). The error is the same and is shown below.

Any help would be gratefully received. Anthony

```
Exception in thread "main" java.lang.IllegalStateException: Cannot store more than 2 beta Bridge in one residue
	at org.biojava.nbio.structure.secstruc.SecStrucState.setBridge(SecStrucState.java:150)
	at org.biojava.nbio.structure.secstruc.SecStrucPred.registerBridge(SecStrucPred.java:294)
	at org.biojava.nbio.structure.secstruc.SecStrucPred.findBridges(SecStrucPred.java:364)
	at org.biojava.nbio.structure.secstruc.SecStrucPred.detectStrands(SecStrucPred.java:119)
	at org.biojava.nbio.structure.secstruc.SecStrucPred.predict(SecStrucPred.java:103)
```

**Comment by lafita** [comment] 2016-01-05 14:54
Hi @abradle, 

The **secondary structure prediction** is a new feature for the next **BioJava** release.  The purpose is to reproduce identically the assignment made by the original **DSSP** algorithm (implemented in C++). Note that we are still working on it.

The exception you are getting can be explained by the following:
- Only 2 beta Bridges can be assigned to a residue (by definition).
- There can be up to 4 hydrogen bonds per residue. 
- Thus, exists the possibility that a residue forms more than 2 beta Bridges, although the probability should be very low.
- The way the original DSSP chooses the 2 beta Bridges (if more than 2 are present) to consider is unknown, so the result will not be guaranteed to be identical.

We preferred to throw an **Exception** in that case, since the result is not guaranteed to be identical to the **DSSP** result. However, we did not find an example where that happened in our tests. As you suggest it may be more frequent than what we thought, could you provide the other (or some more) PDB codes where the exception occurs? We will include them in our test cases.

The idea is to figure out how **DSSP** implements this detail and print a warning (or info message) only. Until then, I propose you to catch any **Exception** that occurs in the SS prediction and load the original DSSP result from the the PDB website. The code could be something like:

```java
    String pdbID = "5pti";
    AtomCache cache = new AtomCache();

    //Load structure without any SS assignment
    Structure s = cache.getStructure(pdbID);

    //Predict and assign the SS of the Structure
    SecStrucPred ssp = new SecStrucPred(); //Instantiation needed
   
    try {
        ssp.predict(s, true); //predict with BioJava the SS and assign it
    } catch (Exception e) {
        e.printStackTrace();
        DSSPParser.fetch(pdbID, s, true); //download from PDB the DSSP result
    }
```
You can find more examples regarding secondary structure prediction, parsing and analyzing in the [Chapter 15 of the BioJava tutorial](https://github.com/biojava/biojava-tutorial/blob/master/structure/secstruc.md).

I will leave the issue open until the fix is made.
Thank you for reporting the issue!

**Comment by darnells** [comment] 2016-01-05 18:35
@lafita, why is this feature (and associated class) called "secondary structure **prediction**?" DSSP is a secondary structure **assignment** algorithm. Secondary structure is predicted when the atomic coordinates are not known.

**Comment by josemduarte** [comment] 2016-01-05 18:46
I think this should simply be a warning, I'd go with printing the warnings and ignoring the beta bridges for anything above 2. In any case it's worth checking that we match DSSP as close as possible, but I wouldn't be surprised if that's their approach too.

I also agree with @darnells that we should talk about __assignment__ and not __prediction__. In the context of bioinformatics, secondary structure prediction is associated with prediction from sequence.

**Comment by darnells** [comment] 2016-01-05 19:20
Since this is still a not-yet-released feature, it is important to change the class name and public API (e.g. SecStrucPred to SecStrucAssign, predict() to assign()) before it is released. Javadoc should also be updated for completeness. Released APIs should remain as static as possible to minimize maintenance for users.

**Comment by lafita** [comment] 2016-01-07 11:50
I completely agree with you @darnells, but the API was present in **BioJava** from previous releases. The feature was never used because the algorithm was not producing correct results (see issue #112), so the changes in this release have been inside the algorithm. If I am not mistaken, @andreasprlic created the API when porting the code from python, so he may have some justifications for the names. I think this is the right time if we want to change any API names. I propose **SecStrucCalc** and **calculate()**, because there exists the possibility to calculate the SS without storing the results into the `Structure` (what would be called assignment), but I am also fine with the proposed name.

@josemduarte I will try your approach and check that the results in those cases are identical. Otherwise we will have to look inside the C++ code of the original DSSP. In any case, I will change the behavior by printing a warning with something like:

`Residue 14 forms more than 2 beta Bridges, DSSP assignment may differ.`

**Comment by andreasprlic** [comment] 2016-01-08 19:00
The class and method names are definitely misleading. https://github.com/biojava/biojava/commit/d4597c48c59ea0821b5643860d33d39640bac5f4 should address this.

**Comment by lafita** [comment] 2016-01-11 10:53
Thank you @andreasprlic for the naming changes. I have done the proposed changes: **ignore** any extra Bridges and **print a warning** when that happens, in 6ecd35e.

I added the example into the **TestSecStrucCalc** and the DSSP result and the BioJava result coincide (and the warning is printed). It could be that @josemduarte is correct in the assumption or it may be just a coincidence.

@abradle could you provide us more examples where the mentioned **Exception** occurred? If you update your BioJava version to any commit following this one you will not need to use the **try-catch** clause I proposed you earlier.

We should maybe leave this issue open until we have some more cases where >2 Bridges in a residue occur.

**Comment by sbliven** [comment] 2016-01-11 11:15
Do we use the correct 2 bridges in the case of 2K4T?

**Comment by lafita** [comment] 2016-01-11 13:49
I have looked a bit more into detail the **2K4T** example. Residues 67 and 68 are at the beginning of an antiparallel beta strand. They form Bridges to the same residue, number 88, which in turn forms a Bridge with residue 96. That is why there are three Bridges assigned to residue 88. I realized that there is no information loss, because Bridges are stored twice (in each of the two residues forming the Bridge), so the Bridge that is not stored in residue 88 is stored in any of the other residues. 
Answering to @sbliven, for this case we use all 3 Bridges, but a difference might occur in the **.dssp** output file generated, because it is not guaranteed that we store (and output) the same 2 Bridges for residue 88. In BioJava Bridges 67 and 68 are printed, and in DSSP Bridges 67 and 96 are printed. I consider this difference a detail without importance, because all Bridges can be reconstructed from any of the two variant files (redundant information).

Thinking in the worst case, the information loss would only occur when two residues with 2 Bridges each form a Bridge between them. This Bridge could not be stored in any of them, so it will not be considered. Taking into account the low probability of three Bridges occurring in one residue, we can neglect the probability of the event occurring twice in the same protein, with the addition that the two residues are connected. 

I will modify the warning and print it only when this latter case happens (when information is lost by ignoring a Bridge), instead of when 3 Bridges occur in a residue.

**Closed** 2016-01-13 09:22 UTC
