### ISSUE TITLE
Finish implementation of secondary structure detection

### ISSUE THREAD

**Issue by andreasprlic** [biojava/biojava#112] opened 2014-04-03 20:39 UTC
The SecStruc.java class contains the beginnings of  some code that can detect secondary structure in proteins, according to the DSSP rules. However there are still some numerical differences and probably bugs and I could not get it yet to produce exactly the same results as is shown e.g. in http://www.pdb.org/pdb/files/5pti.dssp

**Comment by lafita** [comment] 2015-09-21 14:30
How is the current state of the SecStruct.java class? @andreasprlic 

Since the secondary structure is not parsed by default in BioJava I would be interested in using a DSSP implementation to calculate it afterwards if needed. I could spend some time reviewing the code and writing some tests, if it makes sense.

**Comment by andreasprlic** [comment] 2015-09-22 00:09
If I remember correctly, the key difference is that the hydrogen bonds energies that I got were not exactly the same as what DSSP produces. There is still some bug there. It should be possible to get numerically the same values... As a consequence the secondary structure assignments were not exactly the same.  

Please feel free to take a look at it and fix. For comparison you can use the energies reported in the .dssp file linked to above, and you can also take a look at the Jmol implementation of this.

There should be only differences to the .dssp energies, if the BioJava data model loads the PDB data in a different way.

**Comment by lafita** [comment] 2015-09-22 13:21
The DSSP implementation used by PDB is also available as open source, but it is written in C++. Find all the versions here: ftp://ftp.cmbi.ru.nl/pub/software/dssp. 

From the version 2.1.0 upwards the algorithm produces a different output because of pi-helices, and it seems that the version used by PDB is the original one (files are before 2011). 

Is it possible (and a good idea) to port the methods from the C++ implementation? That will really ensure that the output is the same.

**Comment by andreasprlic** [comment] 2015-09-22 21:37
I am pretty sure the BioJava version can do Pi helices as well. (it has support for helices that have hydrogen pattern to residue +3,4,5 ).

It seems that DSSP is now available under the free Boost software license. As such porting the code to Java should be acceptable. However I believe the already existing BioJava implementation is progressed pretty far ahead, so it might be easier to track down the bug in hydrogen bonding energies and then the rest should be already mostly in place.

**Comment by lafita** [comment] 2015-09-23 14:08
I will also create a DSSP File Parser that can be used either for testing the output of the DSSP implementation or for downloading and extracting the information from the DSSP files on the PDB.

**Comment by lafita** [comment] 2015-09-23 14:34
And I think it also makes sense to change the **toString()** method to generate the same DSSP output format, so that it can be parsed again or reused by other programs (as if it was a DSSP output).

**Comment by josemduarte** [comment] 2015-09-23 21:09
Regarding DSSP parser we have an implementation in https://github.com/eppic-team/owl/blob/master/src/main/java/owl/core/runners/DsspRunner.java that we could try to port to Biojava. What we would need also is a data structure to hold the whole secondary structure annotation so that it can be looked up, we had something along those lines in https://github.com/eppic-team/owl/blob/master/src/main/java/owl/core/structure/features/SecondaryStructure.java

**Comment by lafita** [comment] 2015-10-05 15:13
[5pti_biojava.txt](https://github.com/biojava/biojava/files/7767/5pti_biojava.txt)

I already implemented parser and writer for DSSP file format. This is the output that the biojava implementation gives for the above entry. You can compare the results with the link below to the DSSP original output. 

The energies are all the same, so there is no bug in the energy calculation.

However, the SS assignment differs a bit (the biojava one is larger, more extended in helices and sheets). I will review the threshold for the HBond definition.

**Comment by josemduarte** [comment] 2015-10-05 21:23
Great stuff @lafita! Definitely the issue with differening assignments sounds like a threshold issue. Do the DSSP people document exactly what their thresholds are?

**Comment by andreasprlic** [comment] 2015-10-06 00:42
Great! Then the problem must be either in the H-bond definition, or the detection of h-bond patterns...

**Comment by lafita** [comment] 2015-10-06 16:48
EUREKA! I found the bug that was causing the wrong SS assignment. The indices of the Ladders were not properly set when a new Ladder was created, and that produced very long extended regions. See new result: [5pti_biojavaFix.txt](https://github.com/biojava/biojava/files/8647/5pti_biojavaFix.txt)

In summary there are two bugs fixed now:
- The third column of the **energies** was not correctly printed, which was interpreted as a bug in the energies, but they are correctly calculated.
- The **Ladders** were initialized with changed indices and that made them longer than expected. 
- In addition, all the thresholds (i,e. for H-Bond definition and minimum CA distance) are exactly the same as in the original DSSP implementation (I checked in their C++ code).

However, there are still some subtle differences with the original DSSP implementation, which can be discussed if they are desired properties or not:
- The **first residue** of the protein is always omitted from any H-Bond formation, because the H atom is not calculated (the current formula for calculating the H atoms requires a peptide bond). You can see that the BioJava implementation has all 0s for the energies in the first row, but the DSSP implementation has some energies calculated (they are very weak and not forming an H-Bond). Should we include the first residue? This might be important if it is involved in a SS element, like a helix or a strand.
- The **helices** do not have a minimum number of residues. The original DSSP and the Jmol implementation only consider helices if the number of turns is above a threshold, but our implementation tags as an alpha helix 4 consecutive turns (like in the example of 5pti).
- The helices seem to be longer in some cases, which is linked to the previous comment. I remember you already commented something about that @andreasprlic, but I do not remember if it was a bad DSSP decision or a bug in our implementation.

A part from this comments, the BioJava implementation for SS prediction should be working as expected, and we can even expose some parameters to the user to make it more flexible and customizable. A pull request is coming with the changes and other support for SS that I will list.

**Comment by josemduarte** [comment] 2015-10-06 16:56
Awesome! Regarding your points about first residue and short helices I'd vote for matching the DSSP implementation as much as possible. At the end of the day all these are definitions and a bit arbitrary. DSSP is the _de facto_ standard and as such we should follow it as close as possible.

**Comment by andreasprlic** [comment] 2015-10-07 11:54
It could be a parameter to read original dssp or "improved". The original code assigns helices too short IMHO. 

About the hydrogens : there are two internal implementations for placement of the H. Again, one exactly as dssp has it and one slightly improved. Which in some cases can result in subtle differences in assignments.

**Comment by andreasprlic** [comment] 2015-10-07 11:58
Btw, did you try to run the code for a large protein, such as a ribosome? This can really solve the problem how to get dssp assignments, if there are no pdb files available.

**Comment by lafita** [comment] 2015-10-07 13:46
Yes, it runs for big proteins. I tried Yeast 80S ribosome:
[4V7R..dssp.txt](https://github.com/biojava/biojava/files/9374/4V7R.dssp.txt)

It takes about 10 seconds to run.

**Comment by lafita** [comment] 2015-10-07 14:51
The problem with the first residue is solved! It was not a problem with the hydrogen, but because a loop ignored the first position, starting at 1. Now the output for the energies matches exactly the DSSP implementation. 
[5pti.dssp.txt](https://github.com/biojava/biojava/files/9425/5pti.dssp.txt)

**Comment by lafita** [comment] 2015-10-12 15:42
I fixed a couple of bugs more, specially with the turns and helices. Now it is possible to reproduce the exact same DSSP results (if a flag for short helices is set) or obtain the results with full helices (even the authors say in the paper that helices are one residue shorter at both ends than they should be). However, in very special cases like short beta bridges and irregular helices, one residue assignment is different. I haven't figured out what is exactly happening, but the changes are minor (like a G where a T should be, or a B insted of a three residue sheet, which is a difficult claim). I will continue investigating. For 5pti the results are now exactly the same, but for bigger proteins these small differences occur. Are they so relevant?

**Comment by andreasprlic** [comment] 2015-10-12 18:55
The described differences indicate that there are still a few minor issues. The B vs the 3-residue sheet seems to be a small bug in detecting "ladders", that form the core of sheets. Perhaps the loop that checks which "B"s form the extended sheets terminates too early or starts one residue too far off,(or something like that). 

Do you have the code for this in a branch?

**Comment by lafita** [comment] 2015-10-12 20:48
All the changes I have been doing are in my branch [secstruc](https://github.com/lafita/biojava/tree/secstruc). If you want to have a look, the SecStrucPred class in secstruc package contains the DSSP algorithm and a test called TestSecStrucPred can be run to debug and see example outputs. 

The main problem seems to be that some beta bridges are not identified, because when I print the results, I find that some are missing compared to the DSSP output (I think ladder extension is ok) However, I have used exactly the same indices described in the paper to identify beta bridges, and using those indices I have debugged the cases where it happens and the result is as expected (but different to DSSP). I wonder if the DSSP implementation uses other heuristics different than the paper description to identify beta bridges, because the Jmol output is the same as the DSSP one.

To see an example where the B instead of EEE happens run the [Test](https://github.com/lafita/biojava/blob/secstruc/biojava-structure/src/test/java/org/biojava/nbio/structure/secstruc/TestSecStrucPred.java) for the entry 1ze3 and compare it to the DSSP output http://www.rcsb.org/pdb/files/1ze3.dssp. The difference happens in the antiparallel sheet 2,3,4-24,23,22. The energies, which are the same for BioJava and DSSP, seem to indicate that only an antiparallel bridge between 3 and 23 exist, and the other residues do not have significant HBond energies. Probably I am missing something...

If you check the output for 5pti, the predictions match perfectly, so we have made some improvement already.

**Comment by andreasprlic** [comment] 2015-10-12 21:05
If jmol is identical to DSSP,  you could compare your implementation with the method ```getSheetStructures``` in http://sourceforge.net/p/jmol/code/HEAD/tree/trunk/Jmol/src/org/jmol/dssx/DSSP.java#l522

**Comment by lafita** [comment] 2015-10-13 13:49
Fixed! Thanks to @sbliven. The results are now the same!!!

**Comment by andreasprlic** [comment] 2015-10-13 18:34
awesome!! please push to the main branch then!

**Closed** 2015-10-28 09:49 UTC
Labels: enhancement, new feature
