### ISSUE TITLE
Travis-CI not running for negative credit balance

### ISSUE THREAD

**Issue by aalhossary** [biojava/biojava#958] opened 2021-08-23 04:18 UTC
Travis-CI does not run BioJava for some reason related to negative balance!!!
Here is the error message
**Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.**

**Comment by aalhossary** [comment] 2021-08-24 21:44
Update: It seems that `remoteURL.openStream(); ` is working back now.
I will update the issue text and title

**Comment by josemduarte** [comment] 2021-08-28 20:40
Thanks for catching it @aalhossary . It does look like we have run out of credits on the free-plan at travis-ci.com. I don't see how or when we will get more credits. After some googling, it seems this is a common problem. 

Is the only solution dropping travis-ci and using github workflows only? Any experience on this anyone?

**Comment by aalhossary** [comment] 2021-08-29 08:57
The only experience I have is rerunning the same tests from my (personal) travis-ci account, considering that my BioJava is a clone of the BioJava/BioJava.

There is no harm in giving GitHub workflow actions a try.

**Comment by sbliven** [comment] 2021-09-17 19:30
Related to #952.

**Comment by josemduarte** [comment] 2021-09-20 18:51
I'll close this as duplicate of #952 . We'll continue the discussion there.

**Closed by josemduarte** 2021-09-20 18:51 UTC
