### ISSUE TITLE
AbstractFastqReader should be public

### ISSUE THREAD

**Issue by kerner1000** [biojava/biojava#347] opened 2015-11-11 22:42 UTC
<code>org.biojava.nbio.sequencing.io.fastq.AbstractFastqReader</code> is package private, so cannot be extended.

**Comment by heuermh** [comment] 2015-11-11 23:36
That is by design.  What is your use case for extending ```AbstractFastqReader```?

**Comment by kerner1000** [comment] 2015-11-12 08:41
As mentioned in the other issue, I was planning to just extend <code>AbstractFastqReader</code> in order to implement a handy and performant stream/ <code>Iterator</code>-based reading.

**Comment by andreasprlic** [comment] 2016-01-09 16:23
Can we close this ?

**Comment by heuermh** [comment] 2016-01-09 17:06
I believe so, thanks!

**Closed by heuermh** 2016-01-09 17:06 UTC
